### ISSUE TITLE
Make front page searchable

### ISSUE THREAD

**Issue by schneiderstefan** [yvon/iracing-data-api-client#1]
I'm loving this website. Thank you for creating it.

If I may make a suggestion, I find it quite hard to find the series that I care about on the front page. It would be very useful if it was possible to search (ctrl-f) the page. As it only contains pictures, this is currently not possible.

**Comment by yvon** [comment]
Thank you for the suggestion, I will do it!

**Comment by yvon** [comment]
Sorry it took me a while but here we go:

![image](https://github.com/yvon/iracing-data-api-client/assets/23889/cf98bbc2-55ce-4260-a988-fd9c0c5b2af2)

You'll find the series in plain text below the logos.
